# Dimension
The term "dimension" refers to the number of indices or axes needed to uniquely identify an element in an array.

A 1D array has 1 dimension (like a list): e.g., [1, 2, 3].
A 2D array has 2 dimensions (like a matrix): e.g., [[1, 2], [3, 4]].
A 3D array has 3 dimensions (like a cube or a stack of matrices): e.g., [[[1, 2], [3, 4]], [[5, 6], [7, 8]]].

In [1]:
import numpy as np

arr_1d = np.array([1, 2, 3])
print(arr_1d.ndim)  # Output: 1

arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.ndim)  # Output: 2

1
2


# Axis
An axis refers to a specific dimension along which operations can be performed.

Axis 0 refers to the "rows" in a 2D array (or the first dimension in general).
Axis 1 refers to the "columns" in a 2D array (or the second dimension in general).
Higher axes (e.g., Axis 2, Axis 3) refer to subsequent dimensions in higher-dimensional arrays.
When performing operations on arrays (like summing or taking the mean), you can specify the axis along which to operate.

For a 3D array, axes are numbered as follows:

Axis 0: First dimension <b>(depth or outermost arrays)</b>.</br>
Axis 1: Second dimension (rows of each matrix).</br>
Axis 2: Third dimension (columns of each matrix)

In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Sum along Axis 0 (column-wise sum)
print(np.sum(arr_2d, axis=0))  # Output: [5, 7, 9]

# Sum along Axis 1 (row-wise sum)
print(np.sum(arr_2d, axis=1))  # Output: [ 6, 15]

[5 7 9]
[ 6 15]


In [10]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("original array")
print(arr_3d)
print("sum axis 0")
# Sum along Axis 0
print(np.sum(arr_3d, axis=0))  # Output: [[ 6  8], [10 12]]

print("Sum axis 1")
# Sum along Axis 1
print(np.sum(arr_3d, axis=1))  # Output: [[ 4  6], [12 14]]

print("Sum axis 2")
# Sum along Axis 2
print(np.sum(arr_3d, axis=2))  # Output: [[ 3  7], [11 15]]

original array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
sum axis 0
[[ 6  8]
 [10 12]]
Sum axis 1
[[ 4  6]
 [12 14]]
Sum axis 2
[[ 3  7]
 [11 15]]


# 1 - 1D array creation functions

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

# 2 - 2D array creation functions

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [16]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

# 3 - general ndarray creation functions

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# 3) Replicating, joining, or mutating existing arrays

No copy at all: Simple assignments make no copy of objects or their data.

In [22]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a 
b is a 

True

View or shallow copy: Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [24]:
c = a.view()
c is a

False

Deep copy: The copy method makes a complete copy of the array and its data.

In [26]:
d = a.copy()
d is a

False

# vstack (Consider one sign)

Stack arrays in sequence vertically (row wise).
This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N). 

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# hstack (Consider one horizontal sign)

This is equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis.

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [32]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Indexing on ndarrays

Single element indexing

In [33]:
x = np.arange(10)

In [35]:
display(x[2])
display(x[-2])

2

8

In [39]:
x.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
x[1, 3]

8

In [38]:
x[1, -1]

9

Note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [40]:
x[0]

array([0, 1, 2, 3, 4])

In [41]:
x[0][2]

2

In [43]:
x[0, 2] == x[0][2]

True

# Slicing and striding

In [44]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [45]:
x[-2:10]

array([8, 9])

In [46]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [47]:
x[5:]

array([5, 6, 7, 8, 9])

In [65]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [50]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [63]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr = np.arange(27).reshape(3, 3, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
print(arr[...,0])

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [60]:
# Extracting a single element
print(arr[1, ..., 2]) 

[11 14 17]


In [61]:
# Slicing specific dimensions
print(arr[1, ..., :2])

[[ 9 10]
 [12 13]
 [15 16]]


In [66]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [68]:
arr.shape

(3, 3, 3)

In [75]:
arr[:, np.newaxis, :, :].shape

(3, 1, 3, 3)

In [76]:
arr[:, None, :, :].shape

(3, 1, 3, 3)

# Advanced indexing

Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view).

In [78]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [79]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [80]:
x[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])

In [81]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In this example, the first index value is 0 for both index arrays, and thus the first value of the resultant array is y[0, 0]. The next value is y[2, 1], and the last is y[4, 2].

In [82]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [86]:
y[np.array([0, 2, 4]), 1]

array([ 1, 15, 29])

In [87]:
y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [88]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [90]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [93]:
x[~np.isnan(x)]

array([1., 2., 3.])

In [94]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [95]:
x = np.arange(35).reshape(5, 7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [96]:
b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [97]:
b[:, 5]

array([False, False, False,  True,  True])

In [98]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

# Broadcasting

In [99]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [100]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

# General broadcasting rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

1. they are equal, or

2. one of them is 1.

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes.

In [103]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

In [104]:
b = np.array([1.0, 2.0, 3.0])
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [105]:
a = np.array([0.0, 10.0, 20.0, 30.0])
a

array([ 0., 10., 20., 30.])

In [106]:
b = np.array([1.0, 2.0, 3.0])

In [107]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [109]:
a[:, np.newaxis] + b # Outer product

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# A practical example: vector quantization

In [110]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])

In [111]:
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])

In [113]:
diff = codes - observation    # the broadcast happens  
diff

array([[ -9.,  15.],
       [ 21.,   5.],
       [-66., -33.],
       [-54., -15.]])

In [114]:
dist = sqrt(sum(diff**2,axis=-1))
dist

array([17.49285568, 21.58703314, 73.79024326, 56.04462508])

In [115]:
argmin(dist)

0

# View

It is possible to access the array differently by just changing certain metadata like stride and dtype without changing the data buffer. This creates a new way of looking at the data and these new arrays are called views. The data buffer remains the same, so any changes made to a view reflects in the original copy.

# Copy

When a new array is created by duplicating the data buffer as well as the metadata, it is called a copy. Changes made to the copy do not reflect on the original array. Making a copy is slower and memory-consuming but sometimes necessary

In [116]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
y = x[1:3]  # creates a view
y

array([1, 2])

In [119]:
x[1:3] = [10, 11]
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [121]:
y # Here, y gets changed when x is changed because it is a view.

array([10, 11])

The numpy.reshape function creates a view where possible or a copy otherwise