# Initializing a Tensor

In [1]:
import torch
import numpy as np

In [7]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9748, 0.1676],
        [0.8777, 0.0361]]) 



In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2618, 0.8040, 0.7356],
        [0.1835, 0.5014, 0.3445]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

torch.tensor() creates a tensor that always copies the data from the input object. torch.from_numpy() creates a tensor that always shares memory from NumPy arrays

In [13]:
b = torch.asarray(a) # Shares memory with tensor 'a'
b

tensor([1, 2, 3])

In [14]:
c = torch.asarray(a, copy=True) # Forces memory copy
c

tensor([1, 2, 3])

In [15]:
a.data_ptr() == c.data_ptr()

False

In [16]:
a = torch.tensor([1., 2., 3.], requires_grad=True)
a

tensor([1., 2., 3.], requires_grad=True)

In [17]:
b = a + 2
b

tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [18]:
# Shares memory with tensor 'b', with no grad
c = torch.asarray(b)
c

tensor([3., 4., 5.])

In [20]:
c is b

False

In [21]:
# Shares memory with tensor 'b', retaining autograd history
d = torch.asarray(b, requires_grad=True)
d

tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [23]:
torch.asarray(a) 

tensor([1., 2., 3.])